[phases.setup]
nixPkgs = ["python312", "git", "gcc", "g++", "make", "libopenblas", "python3-dev"]

[phases.install]
cmds = ["python -m venv /app/.venv", "source /app/.venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python app.py"
